REM 13201 is Configuration Service, uncomment if needed
netsh http add urlacl url=https://+:13200/ConfigService/rest user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13201/ConfigService user="NT AUTHORITY\SYSTEM"

REM Range below is for web
netsh http add urlacl url=http://+:13202/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13300/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13301/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13302/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13303/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13304/ClientMessageService user="NT AUTHORITY\SYSTEM"

REM Range below is for Async Job Engine service
netsh http add urlacl url=http://+:13305/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13306/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13307/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13308/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13309/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13310/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13311/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13312/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13313/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13314/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13315/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13316/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13317/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13318/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13319/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13320/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13321/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13322/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13323/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13324/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13325/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13326/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13327/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13328/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13329/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13330/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13331/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13332/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13333/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13334/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13335/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13336/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13337/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13338/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13339/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13340/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13341/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13342/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13343/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13344/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13345/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13346/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13347/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13348/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13349/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13350/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13351/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13352/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13353/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13354/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13355/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13356/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13357/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13358/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13359/ClientMessageService user="NT AUTHORITY\SYSTEM"
netsh http add urlacl url=http://+:13360/ClientMessageService user="NT AUTHORITY\SYSTEM"

REM 8082 is for Queuing Service, uncomment if needed
netsh http add urlacl url=http://+:8082/QueuingService user="NT AUTHORITY\SYSTEM"

pause